### Imports

In [1]:
# non-native
import pandas as pd 
import numpy as np 
import plotly.express as px
import nbformat # requirement for plotly
from scipy.signal import find_peaks
import dtw

# local
import importlib
import spectral_data_types
from utils.misc import read_in_hdf5_spectra
from utils.plotting import plot_spectra_on_histogram

# dataframes
spectra_df = read_in_hdf5_spectra()

Importing the dtw module. When using in academic works please cite:
  T. Giorgino. Computing and Visualizing Dynamic Time Warping Alignments in R: The dtw Package.
  J. Stat. Soft., doi:10.18637/jss.v031.i07.



In [2]:
# forcefully reloading modules for faster debugging. 
importlib.reload(spectral_data_types)
Particle = spectral_data_types.Particle
Channel = spectral_data_types.Channel

In [3]:
some_spectra = Particle(spectral_dataframe=spectra_df.loc['chan1':'chan91'])
chan1 = some_spectra['chan1']
chan101 = some_spectra['chan101']

In [4]:
chan1_peaks = chan1.scipy_peaks()
chan101_peaks = chan101.scipy_peaks()

LEFTIES
[5146 3091 8801 3091 3091 3091  415  415]
RIGHTIES
[7581 4365 8904 4443 4513 4634 4634 7581]
LEFTIES
[5582 3735 9361 4675 4675 4675  281  281]
RIGHTIES
[8664 4675 9554 4858 4919 5058 5058 8664]


In [5]:
chan1_peaks

(array([ 366,  371,  399, ..., 9979, 9981, 9995], shape=(1940,)),
 array([5345, 4050, 8859, 4435, 4456, 4544, 3051, 4722]),
 {'prominences': array([4., 4., 7., ..., 8., 4., 4.], shape=(1940,)),
  'left_bases': array([ 361,  368,  395, ..., 9971, 9980, 9992], shape=(1940,)),
  'right_bases': array([ 368,  373,  405, ..., 9982, 9982, 9996], shape=(1940,))})

In [6]:
og_indices, indices, data = chan1.scipy_peaks()
data

LEFTIES
[5146 3091 8801 3091 3091 3091  415  415]
RIGHTIES
[7581 4365 8904 4443 4513 4634 4634 7581]


{'prominences': array([4., 4., 7., ..., 8., 4., 4.], shape=(1940,)),
 'left_bases': array([ 361,  368,  395, ..., 9971, 9980, 9992], shape=(1940,)),
 'right_bases': array([ 368,  373,  405, ..., 9982, 9982, 9996], shape=(1940,))}

In [15]:
fig_peaks = px.line(chan1.counts)
fig_locs = px.scatter(
    x =[3091,4443],
    y = [0,0],
    color_discrete_sequence=['red']
)
fig_peaks.add_traces(fig_locs.data)

In [8]:
fig_peaks = px.line(chan1.counts)
fig_locs = px.scatter(x = [chan1_peaks[1]['left_bases'][0], chan1_peaks[1]['right_bases'][0]], y = [0,0], color_discrete_sequence=['yellow'])
fig_peaks.add_traces(fig_locs.data)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
vars(dtw.dtw(x = chan1.counts, y = chan101.counts))

In [ ]:
allignment = dtw.dtw(x = chan1.counts, y = chan101.counts)

In [ ]:
chan1_alligned = px.line(chan1.counts[allignment.index1])
chan101_alligned = px.line(chan101.counts[allignment.index2]+ 1_000,  color_discrete_sequence = ['purple'])
chan1_alligned.add_traces(chan101_alligned.data)

In [ ]:
chan1

In [ ]:
chan1_fig = px.line(chan1.counts)
chan101_fig = px.line(chan101.counts+ 1_000, color_discrete_sequence=['red'])
chan1_fig.add_traces(chan101_fig.data)